name: Basic Build Pipeline

env:
  APP_ENV: testing

jobs:
  install:
    name: Install Dependencies
    pre:
      - name: Set up environment
        run: echo "Preparing workspace..."
    steps:
      - name: Check PHP version
        run: php -v
      - name: Install packages
        run: |
          echo "Loading composer repositories..."
          echo "Installing dependencies..."
          echo "✓ 48 packages installed"
      - name: Verify autoloader
        run: echo "Autoloader optimized."
    post:
      - name: Clean up temp files
        run: echo "Workspace cleaned."

  test:
    name: Run Tests
    needs: install
    pre:
      - name: Bootstrap test database
        run: echo "Creating in-memory database..."
    steps:
      - name: PHPUnit
        run: |
          echo "PHPUnit 11.0 by Sebastian Bergmann and contributors."
          echo ""
          echo "Runtime: PHP 8.3.0"
          echo "Configuration: phpunit.xml"
          echo ""
          printf '..............................                         30 / 30 (100%%)\n'
          echo ""
          echo "Time: 00:02.314, Memory: 12.00 MB"
          echo ""
          printf '\033[32mOK (30 tests, 84 assertions)\033[0m\n'
      - name: Static Analysis
        run: |
          echo "Running PHPStan on src/..."
          printf '\033[32m [OK] No errors\033[0m\n'
    post:
      - name: Publish test report
        run: echo "Test report saved to /tmp/reports/phpunit.xml"

  build:
    name: Build Assets
    needs: test
    steps:
      - name: Compile JS
        run: |
          echo "vite v5.0.0 building for production..."
          echo "transforming..."
          echo "736 modules transformed."
          printf '\033[32mdist/assets/app-Bx3kQ2p.js   142.40 kB │ gzip: 44.32 kB\033[0m\n'
          printf '\033[32mBuilt in 1.83s\033[0m\n'
      - name: Finalize
        run: echo "Artifacts ready."
    post:
      - name: Notify Slack
        run: echo "Deployment notification sent."
